# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-FindDependencies
version:      1.02
version_from: lib/CPAN/FindDependencies.pm
installdirs:  site
requires:
    CPAN:                          1.9102
    LWP::UserAgent:                2.032
    Scalar::Util:                  1.14
    YAML:                          0.61

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
