# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-FindDependencies
version:      1.99_01
version_from: lib/CPAN/FindDependencies.pm
installdirs:  site
requires:
    LWP::Simple:                   1.41
    Module::CoreList:              2.12
    Parse::CPAN::Packages:         2.26
    Scalar::Util:                  1.14
    YAML:                          0.61

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
