---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-FindDependencies
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0.05
  Devel::CheckOS: 1.52
  File::Temp: 0.19
  LWP::UserAgent: 0
  Module::CoreList: 2.9
  Parse::CPAN::Packages: 2.31
  Scalar::Util: 1.14
  URI::file: 4.13
  YAML::Tiny: 1.36
resources: {}
version: 2.42
